DEBUG = False

import os
BASE_DIR = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_DATABASE_URI = 'MYSQL_OR_POSTGRES://USER:PASSWORD@localhost:PORT/DATABASE_NAME'
DATABASE_CONNECT_OPTIONS = {}

THREADS_PER_PAGE = 2

CSRF_ENABLED = True

CSRF_SESSION_KEY = 'secret'

SECRET_KEY = 'PUT_YOUR_SECRET_HERE'